### PR TITLE
adapt name search from JSONTables.jl

### LINKED ISSUE #45: Propertynames of feature collection falsely taken from the first element
I do not know if all GeoJSON features should share the same properties.  But if not, the following is a bit of a nuisance.

With GeoJSON 0.6.0
```
a = """{"type": "FeatureCollection", "features": [
    {"type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[[0.0, 0.0], [1.0, 0.0], [0.0, 1.0], [0.0, 0.0]]]}, "properties": {"foo": "pippo", "bar": "pluto"}},
    {"type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[[0.0, 0.0], [-1.0, 0.0], [0.0, -1.0], [0.0, 0.0]]]}, "properties": {"foo": "fulano"}}
]}"""
b = GeoJSON.read(a)
```
now `propertynames(b)` gives `(:geometry, :bar, :foo)`.

This is same what I get when tab expanding
```
julia> b.<TAB>
bar       foo       geometry
``` 
There is `b.foo`
```
julia> b.foo
2-element Vector{String}:
 "pippo"
 "fulano"
```
but there is no `b.bar`
```
julia> b.bar
ERROR: KeyError: key :bar not found
Stacktrace:
  [1] getindex(h::Dict{Symbol, Int64}, key::Symbol)
    @ Base .\dict.jl:498
  [2] get(obj::JSON3.Object{Base.CodeUnits{UInt8, String}, SubArray{UInt64, 1, Vector{UInt64}, Tuple{UnitRange{Int64}}, true}}, key::Symbol)
    @ JSON3 C:\Users\jaakkor2\.julia\packages\JSON3\GoF7x\src\JSON3.jl:86
  [3] getproperty(obj::JSON3.Object{Base.CodeUnits{UInt8, String}, SubArray{UInt64, 1, Vector{UInt64}, Tuple{UnitRange{Int64}}, true}}, prop::Symbol)
    @ JSON3 C:\Users\jaakkor2\.julia\packages\JSON3\GoF7x\src\JSON3.jl:126
  [4] getproperty(f::GeoJSON.Feature{JSON3.Object{Base.CodeUnits{UInt8, String}, SubArray{UInt64, 1, Vector{UInt64}, Tuple{UnitRange{Int64}}, true}}}, nm::Symbol)
    @ GeoJSON C:\Users\jaakkor2\.julia\packages\GeoJSON\XejMl\src\features.jl:46
  [5] _broadcast_getindex_evalf
    @ .\broadcast.jl:670 [inlined]
  [6] _broadcast_getindex
    @ .\broadcast.jl:643 [inlined]
  [7] getindex
    @ .\broadcast.jl:597 [inlined]
  [8] copyto_nonleaf!(dest::Vector{String}, bc::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(getproperty), Tuple{Base.Broadcast.Extruded{GeoJSON.FeatureCollection{GeoJSON.Feature{JSON3.Object{Base.CodeUnits{UInt8, String}, SubArray{UInt64, 1, Vector{UInt64}, Tuple{UnitRange{Int64}}, true}}}, JSON3.Object{Base.CodeUnits{UInt8, String}, Vector{UInt64}}, JSON3.Array{JSON3.Object, Base.CodeUnits{UInt8, String}, SubArray{UInt64, 1, Vector{UInt64}, Tuple{UnitRange{Int64}}, true}}}, Tuple{Bool}, Tuple{Int64}}, Base.RefValue{Symbol}}}, iter::Base.OneTo{Int64}, state::Int64, count::Int64)
    @ Base.Broadcast .\broadcast.jl:1055
  [9] copy
    @ .\broadcast.jl:907 [inlined]
 [10] materialize
    @ .\broadcast.jl:860 [inlined]
 [11] getproperty(fc::GeoJSON.FeatureCollection{GeoJSON.Feature{JSON3.Object{Base.CodeUnits{UInt8, String}, SubArray{UInt64, 1, Vector{UInt64}, Tuple{UnitRange{Int64}}, true}}}, JSON3.Object{Base.CodeUnits{UInt8, String}, Vector{UInt64}}, JSON3.Array{JSON3.Object, Base.CodeUnits{UInt8, String}, SubArray{UInt64, 1, Vector{UInt64}, Tuple{UnitRange{Int64}}, true}}}, nm::Symbol)
    @ GeoJSON C:\Users\jaakkor2\.julia\packages\GeoJSON\XejMl\src\features.jl:103
 [12] top-level scope
    @ REPL[96]:1
```

### PR DESCRIPTION
**Pull request by rafaqz**
Use the JSONTables.jl methods of getting a list of column names and types. Unfortunately we cant just use their methods as we need to dig into the `properties` field of each object, rather than using the top level fields.

~~@visr this isn't quite finished, just pushing so you know I'm working on it and we don't duplicate efforts~~

So it turned out to be quite tricky getting this to work for both Object and NameTuple features.

There are likely still some issues with vectors of mixed field `NamedTuple` in broadcast or other places, but mostly things seem to be working. 

See #48
Fixes #45

### CODE REVIEW

File: src/features.jl [hunk 1]
```diff
@@ -164,3 +195,63 @@ type(x) = String(x.type)
...
+                    push!(names, k)
+                    types[k] = Union{Missing, missT(typeof(v))}
+                end
+            end
+        end
+    end
+    return names, types
+end
+
+# Handle JSON where the properties are always in .properties
```
Comment (visr) [inline src/features.jl:254]: Can be removed?

File: src/features.jl [hunk 2]
```diff
@@ -164,3 +195,63 @@ type(x) = String(x.type)
...
 
 Base.show(io::IO, ::MIME"text/plain", x::GeoJSONObject) = show(io, x)
+
+# Adapted from JSONTables.jl jsontable method
+# We can simply use their method as we need the key/valu pairs
+# of the properties field, rather than the main object
+function property_schema(features)
+    # Short cut for concrete eltypes of NamedTuple
+    if features isa AbstractArray{<:NamedTuple} && isconcretetype(eltype(x))
+        f1 = first(x)
```
Comment (visr) [inline src/features.jl:205]:
```suggestion
    if features isa AbstractArray{<:NamedTuple} && isconcretetype(eltype(features))
        f1 = first(features)
```

Would be good to have a test for this path.

**Review by visr — CHANGES_REQUESTED** [review]
Looks good overall, added some comments. Great to have this.

File: src/features.jl [hunk 3]
```diff
@@ -18,7 +23,9 @@ Feature(geometry::Geometry; kwargs...) =
 
 Access the properties JSON object of a Feature
 """
-properties(f::Feature) = object(f).properties
+properties(obj::JSON3.Object) = obj.properties
+properties(f::Feature{<:JSON3.Object}) = object(f).properties
+properties(f::Feature) = haskey(object(f), :properties) ? object(f).properties : nothing
```
[the remark this answers is not in the document]
Comment (rafaqz) [reply src/features.jl:28]: Ah right I think I wrote that when I misunderstood something and didn't change it back.

File: src/features.jl (hunk 2 above)
Comment (rafaqz) [reply src/features.jl:209]: Done. Found a bug in `show` as we were not always converting `nothing` to `missing` for geometries.

**Comment by rafaqz** [comment]
The current problem is I'm not sure if null geometries are meant to be represented by `nothing` or `missing`.

There is currently a mix ob both in different contexts.

In `getproperty` there is this line:
```julia
 return ifelse(x === nothing, missing, x)
```

And tests reflect this with checks for `missing`. But `geometry(feature)` returns `nothing` without swapping to `missing`.

The main issue with this is round-tripping `Feature` construction doesn't always work. If you build a feature with a `missing` geometry `show` will error in the REPL because the check is for `nothing`. 

I think we need to decide either way, and if its `missing` move where the swap from `nothing` to `missing` happens so its more consistent.

**Comment by rafaqz** [comment]
@visr do you want to have a look at this?

**Comment by visr** [comment]
> Is this so the table column will be a Union{Missing,GeomType} rather than Union{Nothing,Geomtype} ?

Yes this behavior was intended to copy JSONTables. JSON3 by default parses JSON null to nothing, and serialize both nothing and missing to null. And in Julia null elements in data/tables are usually set to missing. That is why JSONTables put some `ifelse(x === nothing, missing, x)` code over it, to present nothing as missing in the tables interface.

I'm not sure what the best approach is here.

**Comment by rafaqz** [comment]
I think how it is now is fine if you take a look at the changes

**Review by visr — APPROVED** [review]
Thanks, this looks good, sorry for the wait.
